# TODO don't run if already installed
- name: Download fonts
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ item.value.filename }}"
    mode: 0755
  loop: "{{ fonts | dict2items }}"
- name: Install fonts # noqa command-instead-of-module
  ansible.builtin.shell:
    cmd: |
      unzip -o {{ item.value.filename }} -d ~/.fonts
      fc-cache -fv
    executable: /bin/bash
  register: result
  changed_when: false
  failed_when: result.rc != 0
  loop: "{{ fonts | dict2items }}"
