# TODO don't run if already installed
- name: Install rogauracore dependencies
  become: yes
  ansible.builtin.package:
    name:
      - libusb-1.0-0
      - libusb-1.0-0-dev

- name: Install rogauracore
  become: yes
  ansible.builtin.shell:
    chdir: /tmp
    cmd: |
      curl -LOs https://github.com/wroberts/rogauracore/releases/download/{{ rogauracore_version }}/rogauracore-{{ rogauracore_version }}.tar.gz
      tar xvf rogauracore-{{ rogauracore_version }}.tar.gz
      cd rogauracore-{{ rogauracore_version }}
      ./configure
      make
      make install
      cd ..
      rm -rf rogauracore-{{ rogauracore_version }}.tar.gz rogauracore-{{ rogauracore_version }}
  register: result
  changed_when: false
  failed_when: result.rc != 0

- name: Register rogauracore to autostart
  vars:
    autostart_script: |
      #!/usr/bin/env xdg-open 
      [Desktop Entry] 
      Type=Application
      Name=rogauracore
      Exec=bash -c "{{ rogauracore_cmd }}"
      StartupNotify=false
      Terminal=false
  ansible.builtin.copy:
    content: "{{ autostart_script }}"
    dest: "{{ home_directory }}/.config/autostart/rogauracore.desktop"
    mode: 0644
