personal:
  hosts:
    EvanAsus:
      ansible_connection: local
    EvanDesktop:
      ansible_connection: local

gnome:
  hosts:
    EvanAsus:
  
kde:
  hosts:
    EvanDesktop:

zephyrus:
  hosts:
    EvanAsus:

servers:
  hosts:
    JacksonBox:
      ansible_host: 192.168.2.16
      ansible_port: 22
      ansible_user: ejackson
      ansible_connection: ssh
      ansible_ssh_pass: "{{ ansible_ssh_pass }}"
    RaspberryPi:
      ansible_host: 192.168.2.15
      ansible_port: 22
      ansible_user: ejackson
      ansible_connection: ssh
      ansible_ssh_private_key_file: "{{ ansible_ssh_pass }}"

folding:
  hosts:
    EvanAsus:
    JacksonBox:
    EvanDesktop:

web:
  hosts:
    JacksonBox:

pi_hole:
  hosts:
    RaspberryPi:
