all:
  hosts:
    EvanDesktop:
      ansible_connection: local
    JacksonBox:
      ansible_host: 192.168.2.16
      ansible_port: 22
      ansible_user: ejackson
      ansible_connection: ssh
      ansible_ssh_pass: "{{ ansible_ssh_pass }}"
    #RaspberryPi:
    #ansible_host: 192.168.2.15
    #ansible_port: 22
    #ansible_user: ejackson
    #ansible_connection: ssh
    #ansible_ssh_private_key_file: "{{ ansible_ssh_pass }}"
    EvanSteamDeck:
      ansible_host: 192.168.2.17
      ansible_port: 22
      ansible_user: deck
      ansible_connection: ssh
      ansible_ssh_pass: "{{ ansible_ssh_pass }}"

desktops:
  hosts:
    EvanDesktop:

servers:
  hosts:
    JacksonBox:
    #RaspberryPi:

web_servers:
  hosts:
    JacksonBox:

#pi_holes:
#hosts:
#RaspberryPi:

steam_decks:
  hosts:
    EvanSteamDeck:

ubuntu:
  hosts:
    EvanDesktop:
    JacksonBox:

development:
  hosts:
    EvanDesktop:
    JacksonBox:
    #RaspberryPi:

flatpak:
  hosts:
    EvanDesktop:
    EvanSteamDeck:

folding:
  hosts:
    EvanDesktop:
    JacksonBox:
