personal:
  hosts:
    EvanAsus:
      ansible_connection: local

servers:
  hosts:
    JacksonBox:
      ansible_host: 192.168.2.11
      ansible_port: 22
      ansible_user: ejackson
      ansible_connection: ssh
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    RaspberryPi:
      ansible_host: 192.168.2.15
      ansible_port: 22
      ansible_user: ejackson
      ansible_connection: ssh
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

folding@home:
  hosts:
    EvanAsus:
    JacksonBox:

web:
  hosts:
    JacksonBox:

pi-hole:
  hosts:
    RaspberryPi:
