personal:
  hosts:
    EvanAsus:
      ansible_connection: local

zephyrus:
  hosts:
    EvanAsus:

servers:
  hosts:
    JacksonBox:
      ansible_host: 192.168.2.16
      ansible_port: 22
      ansible_user: ejackson
      ansible_connection: ssh
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    RaspberryPi:
      ansible_host: 192.168.2.15
      ansible_port: 22
      ansible_user: ejackson
      ansible_connection: ssh
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

folding:
  hosts:
    EvanAsus:
    JacksonBox:

web:
  hosts:
    JacksonBox:

pi_hole:
  hosts:
    RaspberryPi:
