- name: All devices
  hosts: all
  roles:
    - common

- name: Devices running Ubuntu
  hosts: ubuntu
  roles:
    - ubuntu

- name: Devices that use Flatpaks
  hosts: flatpak
  roles:
    - flatpak

- name: Development devices
  hosts: development
  roles:
    - development

- name: Desktop devices
  hosts: desktops
  roles:
    - desktop

- name: Servers
  hosts: servers
  roles:
    - server

- name: Web servers
  hosts: web_servers
  roles:
    - web_server

# - name: Pi-holes
#   hosts: pi_hole
#   roles:
#     - pi_hole

- name: Steam Decks
  hosts: steam_decks
  roles:
    - steam_deck

- name: Devices running Folding@home
  hosts: folding
  roles:
    - folding@home
