- name: Configure autostart applications
  ansible.builtin.include_tasks: autostart.yml

- name: Configure USB wakeup
  ansible.builtin.include_tasks: usb_wakeup.yml

- name: Configure Bluetooth
  ansible.builtin.include_tasks: bluetooth.yml

- name: Configure fonts
  ansible.builtin.include_tasks: fonts.yml

- name: Configure WoeUSB
  ansible.builtin.include_tasks: woeusb.yml

# TODO power settings
# TODO dark mode
# TODO taskbar pins/settings

- name: Keyboard configuration
  ansible.builtin.include_tasks: keyboard.yml
