[Interface]
# Key for JacksonBox
# Bouncing = 17
# NetShield = 0
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = 2GwOBvfnGoimVzktzaWeq8/PwZioYvpESZHB81iRMFs=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# CA#593
PublicKey = SFesR+3u5/vyQGeaCSREjs4m2WznwFlWAQ9CE3QSnRg=
AllowedIPs = 0.0.0.0/0
Endpoint = 104.254.95.98:51820