# System vars
hostname: JacksonBox
domain: jacksonbox.local
timezone: "America/Toronto"
trigger_reboots: true

# User-level vars
username: ejackson
home_directory: "/home/ejackson"
github_key_file: "/home/ejackson/.ssh/id_github_ed25519"
user_shell: /usr/bin/fish
dotfiles_branch: server

# No-login users for owning services
service_users:
  ddclient:
    name: "ddclient"
    uid: 995
    groups: "ddclient"
    gid: 995
  folding:
    name: "folding"
    uid: 1001
    groups: "folding"
    gid: 1001
  media:
    name: "media"
    uid: 911
    groups: "media"
    gid: 911
  minecraft:
    name: "minecraft"
    uid: 996
    groups: "minecraft"
    gid: 996
  netdata:
    name: "netdata"
    uid: 1004
    groups: "netdata"
    gid: 1004
  wireguard:
    name: "wireguard"
    uid: 1003
    groups: "wireguard"
    gid: 1003
  www-data:
    name: "www-data"
    uid: 33
    groups: "www-data"
    gid: 33

# NGINX Docker network shared by services that should be forwarded to the reverse proxy
nginx_network: "nginx_network"

# ddclient
domain_name: "jacksonnet.ca"
ddclient_domains: "geysermc1,minecraft1,sonarr,radarr,nextcloud,vpn"
ddclient_protocol: "namecheap"

# Folding@home
foldingathome_port: "7396"

# Nextcloud
nextcloud_domain_name: "nextcloud.jacksonnet.ca"
nextcloud_data_dir: "/hdd/nextcloud/app/data"

# Media
media_data_dir: "/hdd/home-theater"
home_theater_repo_dest: "{{ home_directory }}/home-theater"
plex_port: "32400"
prowlarr_port: "9696"
bazarr_port: "6767"
qbittorrent_port: "9091"
radarr_domain_name: "radarr.jacksonnet.ca"
sonarr_domain_name: "sonarr.jacksonnet.ca"

# Wireguard
vpn_domain_name: "vpn.jacksonnet.ca"
wireguard_port: "51820"
wireguard_webui_port: "51821"

# Netdata
netdata_port: "19999"

# Minecraft
minecraft_servers:
  minecraft1:
    version: "1.21.4"
    directory: "{{ home_directory }}/minecraft/minecraft1"
    java_port: 25565
    bedrock_port: 19132
    java_options: "-Xms256M -Xmx2G -XX:+UseG1GC"
    custom_plugin_urls: "https://dev.bukkit.org/projects/thizzyz-tree-feller/files/latest,https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar,https://download.luckperms.net/1573/bukkit/loader/LuckPerms-Bukkit-5.4.156.jar,https://github.com/MC-Machinations/PaperTweaks/releases/download/v0.5.0/PaperTweaks.jar"
