- name: Run package-related tasks
  ansible.builtin.include_tasks: apt.yml

# TODO unattended upgrades

- name: Install .debs not available in APT
  ansible.builtin.include_tasks: debs.yml
  loop: "{{ debs | dict2items }}"
  when: debs is defined

- name: Reboot if required
  when: trigger_reboots is defined and trigger_reboots
  block:
    - name: Check for presence of reboot-required file
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      become: true
      when: reboot_required_file.stat.exists
      ansible.builtin.reboot:
