- name: Install packages via pacman
  become: true
  community.general.pacman:
    name:
      - curl
      - flatpak
      - vim
      - stow
    state: present

- name: Ensure vi alias points to vim
  ansible.builtin.lineinfile:
    path: "{{ home_directory }}/.bashrc"
    line: "alias vi=vim"

- name: Configure Filen sync
  ansible.builtin.include_tasks: filen_sync.yml
