- name: Add Docker apt public key - seems to only be required for Ubuntu installations
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7EA0A9C3F273FCD8
  when: ansible_distribution == "Ubuntu"

- name: Run geerlingguy.pip role to install Docker pip package
  ansible.builtin.include_role:
    name: geerlingguy.pip

- name: Run geerlingguy.docker role to install and configure Docker
  ansible.builtin.include_role:
    name: geerlingguy.docker

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  register: add_to_docker_group_result

- name: Create cron job to prune Docker objects
  become: true
  ansible.builtin.cron:
    name: "Run Docker system prune"
    special_time: weekly
    job: "docker system prune -af"
