- name: Pull and run Folding@home container
  community.docker.docker_container:
    name: foldingathome
    pull: always
    image: lscr.io/linuxserver/foldingathome:latest
    restart_policy: unless-stopped
    env:
      PUID: "{{ service_users.folding.uid }}"
      PGID: "{{ service_users.folding.gid }}"
      TZ: "{{ timezone }}"
      MACHINE_NAME: "{{ hostname }}"
    ports:
      - "{{ foldingathome_port }}:7396/tcp"
    volumes:
      - foldingathome_config:/config

- name: Check whether ufw status is active
  ansible.builtin.command: ufw status
  become: true
  changed_when: false
  register: ufw_check

- name: Open Folding@home port in UFW
  become: true
  when: "'inactive' not in ufw_check.stdout"
  community.general.ufw:
    port: "{{ foldingathome_port }}"
    proto: tcp
    rule: allow
    direction: in
    src: "{{ item }}"
  loop: "{{ local_subnets }}"
