- name: Pull and run Calibre container
  community.docker.docker_container:
    name: calibre
    pull: always
    image: lscr.io/linuxserver/calibre:latest
    restart_policy: unless-stopped
    env:
      PUID: "{{ service_users.calibre.uid }}"
      PGID: "{{ service_users.calibre.gid }}"
      TZ: "{{ timezone }}"
    ports:
      - "{{ calibre_port }}:8080/tcp"
    volumes:
      - calibre_config:/config
      - "{{ calibre_library_dir }}:/library"

- name: Pull and run Calibre Web container
  community.docker.docker_container:
    name: calibre-web
    pull: always
    image: lscr.io/linuxserver/calibre-web:latest
    restart_policy: unless-stopped
    env:
      PUID: "{{ service_users.calibre.uid }}"
      PGID: "{{ service_users.calibre.gid }}"
      TZ: "{{ timezone }}"
    ports:
      - "{{ calibre_web_port }}:8083/tcp"
    volumes:
      - calibre_web_config:/config
      - "{{ calibre_library_dir }}:/library"

- name: Open Calibre port in UFW
  become: true
  community.general.ufw:
    port: "{{ calibre_port }}"
    proto: tcp
    rule: allow
    direction: in
    src: "{{ item }}"
  loop: "{{ local_subnets }}"

- name: Open Calibre Web port in UFW
  become: true
  community.general.ufw:
    port: "{{ calibre_web_port }}"
    proto: tcp
    rule: allow
    direction: in
    src: "{{ item }}"
  loop: "{{ local_subnets }}"
