- name: Configure Calibre
  vars:
    calibre_network: "calibre_internal_network"
  block:
    - name: Create Calibre Docker network
      community.docker.docker_network:
        name: "{{ calibre_network }}"
        internal: false

    - name: Pull and run Calibre container
      community.docker.docker_container:
        name: calibre
        pull: always
        image: lscr.io/linuxserver/calibre:latest
        restart_policy: unless-stopped
        env:
          PUID: "{{ service_users.calibre.uid }}"
          PGID: "{{ service_users.calibre.gid }}"
          TZ: "{{ timezone }}"
        ports:
          - "{{ calibre_http_port }}:8080/tcp"
          - "{{ calibre_https_port }}:8181/tcp"
        volumes:
          - calibre_config:/config
          - "{{ calibre_library_dir }}:/library"
        networks:
          - name: "{{ calibre_network }}"

    - name: Pull and run Calibre Web container
      community.docker.docker_container:
        name: calibre-web
        pull: always
        image: lscr.io/linuxserver/calibre-web:latest
        restart_policy: unless-stopped
        env:
          PUID: "{{ service_users.calibre.uid }}"
          PGID: "{{ service_users.calibre.gid }}"
          TZ: "{{ timezone }}"
          # The following variables allow this container to work with nginx-proxy and acme-companion
          VIRTUAL_HOST: "{{ calibre_web_domain_name }}"
          LETSENCRYPT_HOST: "{{ calibre_web_domain_name }}"
          VIRTUAL_PORT: "8083"
        ports:
          - "{{ calibre_web_port }}:8083/tcp"
        volumes:
          - calibre_web_config:/config
          - "{{ calibre_library_dir }}:/library"
        networks:
          - name: "{{ calibre_network }}"
          - name: "{{ nginx_network }}"

    - name: Open Calibre HTTP port in UFW
      become: true
      community.general.ufw:
        port: "{{ calibre_http_port }}"
        proto: tcp
        rule: allow
        direction: in
        src: "{{ item }}"
      loop: "{{ local_subnets }}"

    - name: Open Calibre HTTPs port in UFW
      become: true
      community.general.ufw:
        port: "{{ calibre_https_port }}"
        proto: tcp
        rule: allow
        direction: in
        src: "{{ item }}"
      loop: "{{ local_subnets }}"

    - name: Open Calibre web port in UFW
      become: true
      community.general.ufw:
        port: "{{ calibre_web_port }}"
        proto: tcp
        rule: allow
        direction: in
        src: "{{ item }}"
      loop: "{{ local_subnets }}"
