- name: Configure Flatpak
  when: flatpaks is defined
  block:
    - name: Install flatpak package
      become: true
      ansible.builtin.package:
        name:
          - flatpak

    - name: Add the Flathub Flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install Flatpaks
      community.general.flatpak:
        name: "{{ item }}"
        state: latest
        method: user
      loop: "{{ flatpaks }}"
