- name: Create groups for service users
  become: true
  ansible.builtin.group:
    name: "{{ item.value.groups }}"
    gid: "{{ item.value.gid }}"
  loop: "{{ service_users | dict2items }}"

- name: Create no-login users for owning services
  become: true
  ansible.builtin.user:
    name: "{{ item.value.name }}"
    uid: "{{ item.value.uid }}"
    groups: "{{ item.value.groups }}"
    shell: /sbin/nologin
    create_home: no
    append: no
  loop: "{{ service_users | dict2items }}"

- name: Add main user to service groups
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    append: true
    groups: "{{ item.value.groups }}"
  loop: "{{ service_users | dict2items }}"
